# Debezium Source Connector (PostgreSQL)
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage=io.debezium.server.redis.RedisOffsetBackingStore
debezium.source.offset.storage.redis.address=redis:6379
debezium.source.offset.storage.redis.key=debezium:offsets

debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=postgres
debezium.source.database.password=postgrespassword
debezium.source.database.dbname=logistics_db
debezium.source.topic.prefix=logistics_cdc
debezium.source.plugin.name=pgoutput
debezium.source.table.include.list=public.OutboxMessages

# Debezium Sink (RabbitMQ Direct)
debezium.sink.type=rabbitmq
debezium.sink.rabbitmq.connection.host=rabbitmq
debezium.sink.rabbitmq.connection.port=5672
debezium.sink.rabbitmq.connection.username=guest
debezium.sink.rabbitmq.connection.password=guest
debezium.sink.rabbitmq.exchange=logistics.cdc.exchange
debezium.sink.rabbitmq.routingKey=logistics.package.events

# Format Payload (JSON Flat)
debezium.format.value=json
debezium.format.value.schemas.enable=false